In [1]:
import numpy as np

In [2]:
data_train = np.load("../data/train.npz", allow_pickle=True)
data_val = np.load("../data/val.npz", allow_pickle=True)
data_test = np.load("../data/test.npz", allow_pickle=True)

X_train, y_train = data_train["X"], data_train["y"]
X_val, y_val = data_val["X"], data_val["y"]
X_test, y_test = data_test["X"], data_test["y"]

In [3]:
y_train_enc = (y_train == "MS – Ministério da Saúde").astype(np.int32)
y_val_enc = (y_val == "MS – Ministério da Saúde").astype(np.int32)
y_test_enc = (y_test == "MS – Ministério da Saúde").astype(np.int32)

In [4]:
import time

# LightGBM classifier, a gradient boosting framework that uses tree-based learning algorithms
from lightgbm import LGBMClassifier

# CalibratedClassifierCV for probability calibration of classifiers
from sklearn.calibration import CalibratedClassifierCV

# Ensemble classifiers from scikit-learn
# ExtraTreesClassifier and RandomForestClassifier are ensemble methods that use multiple decision trees
# StackingClassifier allows combining multiple classifiers to improve performance
from sklearn.ensemble import (
    ExtraTreesClassifier,
    RandomForestClassifier,
    StackingClassifier,
)

# Linear models from scikit-learn
# LogisticRegression is a linear model for binary classification
# SGDClassifier is a linear classifier using stochastic gradient descent
from sklearn.linear_model import LogisticRegression, SGDClassifier

# Metrics for evaluating classification performance
# accuracy_score, balanced_accuracy_score, classification_report, confusion_matrix, f1_score, matthews_corrcoef
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
)

# Naive Bayes classifier for multinomially distributed data
from sklearn.naive_bayes import MultinomialNB

# K-Nearest Neighbors classifier
from sklearn.neighbors import KNeighborsClassifier

# Neural network-based classifier
from sklearn.neural_network import MLPClassifier

# Support Vector Machine classifiers
# SVC is a support vector classifier with a non-linear kernel
# LinearSVC is a support vector classifier with a linear kernel
from sklearn.svm import SVC, LinearSVC

# Decision tree classifier
from sklearn.tree import DecisionTreeClassifier

# XGBoost classifier, an optimized distributed gradient boosting library
from xgboost import XGBClassifier

In [5]:
import pandas as pd
from typing import List, Tuple


def calculate_evaluation_metrics(
    y_true: pd.Series, y_pred: pd.Series
):
    """
    Calculate evaluation metrics for model predictions.

    Args:
        y_true (pd.Series): The true labels.
        y_pred (pd.Series): The predicted labels.

    Returns:
        Tuple[float, float, float, str, float, np.ndarray]: The calculated metrics including F1 score, balanced accuracy, accuracy, classification report, Matthews correlation coefficient, and confusion matrix.
    """
    f1 = f1_score(y_true, y_pred, average="micro")
    balanced_accuracy = balanced_accuracy_score(y_true, y_pred)
    accuracy = accuracy_score(y_true, y_pred)
    classification_report_str = classification_report(y_true, y_pred)
    matthews_corr_coeff = matthews_corrcoef(y_true, y_pred)
    confusion_matrix_arr = confusion_matrix(y_true, y_pred)

    return (
        f1,
        balanced_accuracy,
        accuracy,
        classification_report_str,
        matthews_corr_coeff,
        confusion_matrix_arr,
    )


def train_and_evaluate_models(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    X_valid: pd.DataFrame,
    y_valid: pd.Series,
    n_jobs: int = -1,
):
    """
    Train multiple models and evaluate their performance.

    Args:
        X_train (pd.DataFrame): The training data.
        y_train (pd.Series): The training labels.
        X_valid (pd.DataFrame): The validation data.
        y_valid (pd.Series): The validation labels.
        n_jobs (int, optional): The number of jobs to run in parallel. Defaults to -1.

    Returns:
        Tuple[pd.DataFrame, List[List]]: A dataframe of the evaluation results and a list of classification reports.
    """
    # Define the models to be trained
    models = [
        (
            "Calibrated-LSVC",
            CalibratedClassifierCV(
                LinearSVC(random_state=271828, class_weight="balanced", dual="auto")
            ),
        ),
        (
            "LR",
            LogisticRegression(
                random_state=271828, n_jobs=n_jobs, class_weight="balanced"
            ),
        ),
        (
            "RF",
            RandomForestClassifier(
                random_state=271828, n_jobs=n_jobs, class_weight="balanced"
            ),
        ),
        (
            "LGBM",
            LGBMClassifier(
                random_state=271828, n_jobs=n_jobs, class_weight="balanced", verbose=-1
            ),
        ),
        (
            "XGB",
            XGBClassifier(
                random_state=271828, n_jobs=n_jobs, class_weight="balanced", verbosity=0
            ),
        ),
        ("MLP", MLPClassifier(random_state=271828)),
        (
            "SGD",
            SGDClassifier(random_state=271828, n_jobs=n_jobs, class_weight="balanced"),
        ),
        ("NB", MultinomialNB()),
        ("LSVC", LinearSVC(random_state=271828, class_weight="balanced", dual="auto")),
        ("KNN", KNeighborsClassifier(n_jobs=n_jobs)),
        ("DT", DecisionTreeClassifier(random_state=271828, class_weight="balanced")),
        (
            "ExtraTrees",
            ExtraTreesClassifier(
                random_state=271828, n_jobs=n_jobs, class_weight="balanced"
            ),
        ),
    ]

    evaluation_results = []
    classification_reports = []

    # Train each model and evaluate its performance
    for model_name, model in models:
        start_time = time.time()  # Record the start time

        try:
            # Train the model
            model.fit(X_train, y_train)
            # Make predictions on the validation set
            predictions = model.predict(X_valid)
        except Exception as e:
            # Handle any exceptions that occur during training or prediction
            print(f"Error {model_name} - {e}")
            continue

        # Calculate evaluation metrics
        (
            f1,
            balanced_accuracy,
            accuracy,
            classification_report_str,
            matthews_corr_coeff,
            confusion_matrix_arr,
        ) = calculate_evaluation_metrics(y_valid, predictions)
        # Store the classification report and confusion matrix
        classification_reports.append(
            [model_name, classification_report_str, confusion_matrix_arr]
        )

        elapsed_time = time.time() - start_time  # Calculate the elapsed time
        # Append the evaluation results
        evaluation_results.append(
            [
                model_name,
                f1,
                balanced_accuracy,
                accuracy,
                matthews_corr_coeff,
                elapsed_time,
                confusion_matrix_arr,
                classification_report_str,
            ]
        )

        # Print the evaluation results
        print(
            f"Name: {model_name} - F1: {f1:.4f} - BACC: {balanced_accuracy:.4f} - ACC: {accuracy:.4f} - MCC: {matthews_corr_coeff:.4f} - Elapsed: {elapsed_time:.2f}s"
        )
        print(classification_report_str)
        print(confusion_matrix_arr)
        print("*" * 20, "\n")

    # Create a DataFrame to store the evaluation results
    results_df = pd.DataFrame(
        evaluation_results,
        columns=[
            "Model",
            "F1",
            "BACC",
            "ACC",
            "MCC",
            "Total Time",
            "Confusion Matrix",
            "Classification Report",
        ],
    )
    # Convert the confusion matrix to a string for better readability in the DataFrame
    results_df["Confusion Matrix"] = results_df["Confusion Matrix"].apply(
        lambda x: str(x)
    )

    return models, results_df, classification_reports

In [ ]:
models, df_results, creports = train_and_evaluate_models(
    X_train, y_train_enc, X_val, y_val_enc, n_jobs=-1
)

Name: Calibrated-LSVC - F1: 0.9630 - BACC: 0.6812 - ACC: 0.9630 - MCC: 0.5061 - Elapsed: 57.40s
              precision    recall  f1-score   support

           0       0.97      0.99      0.98     81917
           1       0.74      0.37      0.49      4181

    accuracy                           0.96     86098
   macro avg       0.85      0.68      0.74     86098
weighted avg       0.96      0.96      0.96     86098

[[81370   547]
 [ 2638  1543]]
******************** 



/home/isaaclourenco/lai/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)


Name: LR - F1: 0.8614 - BACC: 0.8366 - ACC: 0.8614 - MCC: 0.3864 - Elapsed: 6.10s
              precision    recall  f1-score   support

           0       0.99      0.86      0.92     81917
           1       0.23      0.81      0.36      4181

    accuracy                           0.86     86098
   macro avg       0.61      0.84      0.64     86098
weighted avg       0.95      0.86      0.90     86098

[[70780 11137]
 [  798  3383]]
******************** 

Name: RF - F1: 0.9674 - BACC: 0.7411 - ACC: 0.9674 - MCC: 0.5914 - Elapsed: 208.92s
              precision    recall  f1-score   support

           0       0.97      0.99      0.98     81917
           1       0.75      0.49      0.59      4181

    accuracy                           0.97     86098
   macro avg       0.86      0.74      0.79     86098
weighted avg       0.96      0.97      0.96     86098

[[81236   681]
 [ 2130  2051]]
******************** 



/home/isaaclourenco/lai/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Name: LGBM - F1: 0.8865 - BACC: 0.8446 - ACC: 0.8865 - MCC: 0.4239 - Elapsed: 7.62s
              precision    recall  f1-score   support

           0       0.99      0.89      0.94     81917
           1       0.27      0.80      0.41      4181

    accuracy                           0.89     86098
   macro avg       0.63      0.84      0.67     86098
weighted avg       0.95      0.89      0.91     86098

[[72992  8925]
 [  844  3337]]
******************** 

Name: XGB - F1: 0.9671 - BACC: 0.7285 - ACC: 0.9671 - MCC: 0.5816 - Elapsed: 18.68s
              precision    recall  f1-score   support

           0       0.97      0.99      0.98     81917
           1       0.77      0.46      0.58      4181

    accuracy                           0.97     86098
   macro avg       0.87      0.73      0.78     86098
weighted avg       0.96      0.97      0.96     86098

[[81327   590]
 [ 2240  1941]]
******************** 

Name: MLP - F1: 0.9593 - BACC: 0.7713 - ACC: 0.9593 - MCC: 0.5519 - El

In [22]:
df_results.sort_values(by="MCC", ascending=False)

Model        F1      BACC       ACC       MCC   Total Time  \
2                RF  0.967351  0.741120  0.967351  0.591364   208.920608   
4               XGB  0.967130  0.728520  0.967130  0.581592    18.681090   
11       ExtraTrees  0.965191  0.722167  0.965191  0.557685   404.565088   
5               MLP  0.959279  0.771263  0.959279  0.551893  1479.776974   
0   Calibrated-LSVC  0.963007  0.681186  0.963007  0.506115    57.401644   
3              LGBM  0.886536  0.844591  0.886536  0.423884     7.619628   
10               DT  0.934981  0.747940  0.934981  0.420602   832.289294   
6               SGD  0.875746  0.828821  0.875746  0.394651    12.927703   
8              LSVC  0.862320  0.835950  0.862320  0.386784    12.989530   
1                LR  0.861379  0.836591  0.861379  0.386444     6.095995   
9               KNN  0.956898  0.599898  0.956898  0.360461   167.965232   
7                NB  0.956224  0.553583  0.956224  0.306840     1.082078   

                   Confusion Matrix  \
2   [[81236   681]\n [ 2130  2051]]   
4   [[81327   590]\n [ 2240  1941]]   
11  [[81207   710]\n [ 2287  1894]]   
5   [[80238  1679]\n [ 1827  2354]]   
0   [[81370   547]\n [ 2638  1543]]   
3   [[72992  8925]\n [  844  3337]]   
10  [[78239  3678]\n [ 1920  2261]]   
6   [[72152  9765]\n [  933  3248]]   
8   [[70871 11046]\n [  808  3373]]   
1   [[70780 11137]\n [  798  3383]]   
9   [[81532   385]\n [ 3326   855]]   
7   [[81879    38]\n [ 3731   450]]   

                                Classification Report  
2                 precision    recall  f1-score   ...  
4                 precision    recall  f1-score   ...  
11                precision    recall  f1-score   ...  
5                 precision    recall  f1-score   ...  
0                 precision    recall  f1-score   ...  
3                 precision    recall  f1-score   ...  
10                precision    recall  f1-score   ...  
6                 precision    recall  f1-score   ...  
8                 precision    recall  f1-score   ...  
1                 precision    recall  f1-score   ...  
9                 precision    recall  f1-score   ...  
7                 precision    recall  f1-score   ...

In [ ]:
from joblib import dump
import sklearn, numpy as np

classifier = models[0][1]
metadata = {
    "sklearn": sklearn.__version__,
    "numpy": np.__version__
}
dump((classifier, metadata), "../models/lai_ms_model_classifier.joblib")
classifier

CalibratedClassifierCV(estimator=LinearSVC(class_weight='balanced',
                                           random_state=271828))